sudo: required
services:
    - docker


before_install:
    - docker build -t sumitsehgal/docker-react -f Dockerfile.dev .

script:
    - docker run sumitsehgal/docker-react npm run test -- --coverage